/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import java.util.List;

/**
 * This is a model class for CreateGooglePayIntermediateSigningKeyRequest type.
 */
public class CreateGooglePayIntermediateSigningKeyRequest {
    private OptionalNullable<String> signedKey;
    private OptionalNullable<List<String>> signatures;

    /**
     * Default constructor.
     */
    public CreateGooglePayIntermediateSigningKeyRequest() {
    }

    /**
     * Initialization constructor.
     * @param  signedKey  String value for signedKey.
     * @param  signatures  List of String value for signatures.
     */
    public CreateGooglePayIntermediateSigningKeyRequest(
            String signedKey,
            List<String> signatures) {
        this.signedKey = OptionalNullable.of(signedKey);
        this.signatures = OptionalNullable.of(signatures);
    }

    /**
     * Initialization constructor.
     * @param  signedKey  String value for signedKey.
     * @param  signatures  List of String value for signatures.
     */

    protected CreateGooglePayIntermediateSigningKeyRequest(OptionalNullable<String> signedKey,
            OptionalNullable<List<String>> signatures) {
        this.signedKey = signedKey;
        this.signatures = signatures;
    }

    /**
     * Internal Getter for SignedKey.
     * Uma mensagem codificada em Base64 com a descrição de pagamento da chave.
     * @return Returns the Internal String
     */
    @JsonGetter("signed_key")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetSignedKey() {
        return this.signedKey;
    }

    /**
     * Getter for SignedKey.
     * Uma mensagem codificada em Base64 com a descrição de pagamento da chave.
     * @return Returns the String
     */
    public String getSignedKey() {
        return OptionalNullable.getFrom(signedKey);
    }

    /**
     * Setter for SignedKey.
     * Uma mensagem codificada em Base64 com a descrição de pagamento da chave.
     * @param signedKey Value for String
     */
    @JsonSetter("signed_key")
    public void setSignedKey(String signedKey) {
        this.signedKey = OptionalNullable.of(signedKey);
    }

    /**
     * UnSetter for SignedKey.
     * Uma mensagem codificada em Base64 com a descrição de pagamento da chave.
     */
    public void unsetSignedKey() {
        signedKey = null;
    }

    /**
     * Internal Getter for Signatures.
     * Verifica se a origem da chave de assinatura intermediária é o Google. É codificada em Base64
     * e criada usando o ECDSA.
     * @return Returns the Internal List of String
     */
    @JsonGetter("signatures")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<List<String>> internalGetSignatures() {
        return this.signatures;
    }

    /**
     * Getter for Signatures.
     * Verifica se a origem da chave de assinatura intermediária é o Google. É codificada em Base64
     * e criada usando o ECDSA.
     * @return Returns the List of String
     */
    public List<String> getSignatures() {
        return OptionalNullable.getFrom(signatures);
    }

    /**
     * Setter for Signatures.
     * Verifica se a origem da chave de assinatura intermediária é o Google. É codificada em Base64
     * e criada usando o ECDSA.
     * @param signatures Value for List of String
     */
    @JsonSetter("signatures")
    public void setSignatures(List<String> signatures) {
        this.signatures = OptionalNullable.of(signatures);
    }

    /**
     * UnSetter for Signatures.
     * Verifica se a origem da chave de assinatura intermediária é o Google. É codificada em Base64
     * e criada usando o ECDSA.
     */
    public void unsetSignatures() {
        signatures = null;
    }

    /**
     * Converts this CreateGooglePayIntermediateSigningKeyRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateGooglePayIntermediateSigningKeyRequest [" + "signedKey=" + signedKey
                + ", signatures=" + signatures + "]";
    }

    /**
     * Builds a new {@link CreateGooglePayIntermediateSigningKeyRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateGooglePayIntermediateSigningKeyRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.signedKey = internalGetSignedKey();
        builder.signatures = internalGetSignatures();
        return builder;
    }

    /**
     * Class to build instances of {@link CreateGooglePayIntermediateSigningKeyRequest}.
     */
    public static class Builder {
        private OptionalNullable<String> signedKey;
        private OptionalNullable<List<String>> signatures;



        /**
         * Setter for signedKey.
         * @param  signedKey  String value for signedKey.
         * @return Builder
         */
        public Builder signedKey(String signedKey) {
            this.signedKey = OptionalNullable.of(signedKey);
            return this;
        }

        /**
         * UnSetter for signedKey.
         * @return Builder
         */
        public Builder unsetSignedKey() {
            signedKey = null;
            return this;
        }

        /**
         * Setter for signatures.
         * @param  signatures  List of String value for signatures.
         * @return Builder
         */
        public Builder signatures(List<String> signatures) {
            this.signatures = OptionalNullable.of(signatures);
            return this;
        }

        /**
         * UnSetter for signatures.
         * @return Builder
         */
        public Builder unsetSignatures() {
            signatures = null;
            return this;
        }

        /**
         * Builds a new {@link CreateGooglePayIntermediateSigningKeyRequest} object using the set
         * fields.
         * @return {@link CreateGooglePayIntermediateSigningKeyRequest}
         */
        public CreateGooglePayIntermediateSigningKeyRequest build() {
            return new CreateGooglePayIntermediateSigningKeyRequest(signedKey, signatures);
        }
    }
}
