/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for GetAnticipationLimitsResponse type.
 */
public class GetAnticipationLimitsResponse {
    private OptionalNullable<GetAnticipationLimitResponse> max;
    private OptionalNullable<GetAnticipationLimitResponse> min;

    /**
     * Default constructor.
     */
    public GetAnticipationLimitsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  max  GetAnticipationLimitResponse value for max.
     * @param  min  GetAnticipationLimitResponse value for min.
     */
    public GetAnticipationLimitsResponse(
            GetAnticipationLimitResponse max,
            GetAnticipationLimitResponse min) {
        this.max = OptionalNullable.of(max);
        this.min = OptionalNullable.of(min);
    }

    /**
     * Initialization constructor.
     * @param  max  GetAnticipationLimitResponse value for max.
     * @param  min  GetAnticipationLimitResponse value for min.
     */

    protected GetAnticipationLimitsResponse(OptionalNullable<GetAnticipationLimitResponse> max,
            OptionalNullable<GetAnticipationLimitResponse> min) {
        this.max = max;
        this.min = min;
    }

    /**
     * Internal Getter for Max.
     * Max limit
     * @return Returns the Internal GetAnticipationLimitResponse
     */
    @JsonGetter("max")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<GetAnticipationLimitResponse> internalGetMax() {
        return this.max;
    }

    /**
     * Getter for Max.
     * Max limit
     * @return Returns the GetAnticipationLimitResponse
     */
    public GetAnticipationLimitResponse getMax() {
        return OptionalNullable.getFrom(max);
    }

    /**
     * Setter for Max.
     * Max limit
     * @param max Value for GetAnticipationLimitResponse
     */
    @JsonSetter("max")
    public void setMax(GetAnticipationLimitResponse max) {
        this.max = OptionalNullable.of(max);
    }

    /**
     * UnSetter for Max.
     * Max limit
     */
    public void unsetMax() {
        max = null;
    }

    /**
     * Internal Getter for Min.
     * Min limit
     * @return Returns the Internal GetAnticipationLimitResponse
     */
    @JsonGetter("min")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<GetAnticipationLimitResponse> internalGetMin() {
        return this.min;
    }

    /**
     * Getter for Min.
     * Min limit
     * @return Returns the GetAnticipationLimitResponse
     */
    public GetAnticipationLimitResponse getMin() {
        return OptionalNullable.getFrom(min);
    }

    /**
     * Setter for Min.
     * Min limit
     * @param min Value for GetAnticipationLimitResponse
     */
    @JsonSetter("min")
    public void setMin(GetAnticipationLimitResponse min) {
        this.min = OptionalNullable.of(min);
    }

    /**
     * UnSetter for Min.
     * Min limit
     */
    public void unsetMin() {
        min = null;
    }

    /**
     * Converts this GetAnticipationLimitsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetAnticipationLimitsResponse [" + "max=" + max + ", min=" + min + "]";
    }

    /**
     * Builds a new {@link GetAnticipationLimitsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetAnticipationLimitsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.max = internalGetMax();
        builder.min = internalGetMin();
        return builder;
    }

    /**
     * Class to build instances of {@link GetAnticipationLimitsResponse}.
     */
    public static class Builder {
        private OptionalNullable<GetAnticipationLimitResponse> max;
        private OptionalNullable<GetAnticipationLimitResponse> min;



        /**
         * Setter for max.
         * @param  max  GetAnticipationLimitResponse value for max.
         * @return Builder
         */
        public Builder max(GetAnticipationLimitResponse max) {
            this.max = OptionalNullable.of(max);
            return this;
        }

        /**
         * UnSetter for max.
         * @return Builder
         */
        public Builder unsetMax() {
            max = null;
            return this;
        }

        /**
         * Setter for min.
         * @param  min  GetAnticipationLimitResponse value for min.
         * @return Builder
         */
        public Builder min(GetAnticipationLimitResponse min) {
            this.min = OptionalNullable.of(min);
            return this;
        }

        /**
         * UnSetter for min.
         * @return Builder
         */
        public Builder unsetMin() {
            min = null;
            return this;
        }

        /**
         * Builds a new {@link GetAnticipationLimitsResponse} object using the set fields.
         * @return {@link GetAnticipationLimitsResponse}
         */
        public GetAnticipationLimitsResponse build() {
            return new GetAnticipationLimitsResponse(max, min);
        }
    }
}
