/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for GetBalanceResponse type.
 */
public class GetBalanceResponse {
    private OptionalNullable<String> currency;
    private OptionalNullable<Long> availableAmount;
    private OptionalNullable<GetRecipientResponse> recipient;
    private OptionalNullable<Long> transferredAmount;
    private OptionalNullable<Long> waitingFundsAmount;

    /**
     * Default constructor.
     */
    public GetBalanceResponse() {
    }

    /**
     * Initialization constructor.
     * @param  currency  String value for currency.
     * @param  availableAmount  Long value for availableAmount.
     * @param  recipient  GetRecipientResponse value for recipient.
     * @param  transferredAmount  Long value for transferredAmount.
     * @param  waitingFundsAmount  Long value for waitingFundsAmount.
     */
    public GetBalanceResponse(
            String currency,
            Long availableAmount,
            GetRecipientResponse recipient,
            Long transferredAmount,
            Long waitingFundsAmount) {
        this.currency = OptionalNullable.of(currency);
        this.availableAmount = OptionalNullable.of(availableAmount);
        this.recipient = OptionalNullable.of(recipient);
        this.transferredAmount = OptionalNullable.of(transferredAmount);
        this.waitingFundsAmount = OptionalNullable.of(waitingFundsAmount);
    }

    /**
     * Initialization constructor.
     * @param  currency  String value for currency.
     * @param  availableAmount  Long value for availableAmount.
     * @param  recipient  GetRecipientResponse value for recipient.
     * @param  transferredAmount  Long value for transferredAmount.
     * @param  waitingFundsAmount  Long value for waitingFundsAmount.
     */

    protected GetBalanceResponse(OptionalNullable<String> currency,
            OptionalNullable<Long> availableAmount,
            OptionalNullable<GetRecipientResponse> recipient,
            OptionalNullable<Long> transferredAmount, OptionalNullable<Long> waitingFundsAmount) {
        this.currency = currency;
        this.availableAmount = availableAmount;
        this.recipient = recipient;
        this.transferredAmount = transferredAmount;
        this.waitingFundsAmount = waitingFundsAmount;
    }

    /**
     * Internal Getter for Currency.
     * Currency
     * @return Returns the Internal String
     */
    @JsonGetter("currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetCurrency() {
        return this.currency;
    }

    /**
     * Getter for Currency.
     * Currency
     * @return Returns the String
     */
    public String getCurrency() {
        return OptionalNullable.getFrom(currency);
    }

    /**
     * Setter for Currency.
     * Currency
     * @param currency Value for String
     */
    @JsonSetter("currency")
    public void setCurrency(String currency) {
        this.currency = OptionalNullable.of(currency);
    }

    /**
     * UnSetter for Currency.
     * Currency
     */
    public void unsetCurrency() {
        currency = null;
    }

    /**
     * Internal Getter for AvailableAmount.
     * Amount available for transferring
     * @return Returns the Internal Long
     */
    @JsonGetter("available_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Long> internalGetAvailableAmount() {
        return this.availableAmount;
    }

    /**
     * Getter for AvailableAmount.
     * Amount available for transferring
     * @return Returns the Long
     */
    public Long getAvailableAmount() {
        return OptionalNullable.getFrom(availableAmount);
    }

    /**
     * Setter for AvailableAmount.
     * Amount available for transferring
     * @param availableAmount Value for Long
     */
    @JsonSetter("available_amount")
    public void setAvailableAmount(Long availableAmount) {
        this.availableAmount = OptionalNullable.of(availableAmount);
    }

    /**
     * UnSetter for AvailableAmount.
     * Amount available for transferring
     */
    public void unsetAvailableAmount() {
        availableAmount = null;
    }

    /**
     * Internal Getter for Recipient.
     * Recipient
     * @return Returns the Internal GetRecipientResponse
     */
    @JsonGetter("recipient")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<GetRecipientResponse> internalGetRecipient() {
        return this.recipient;
    }

    /**
     * Getter for Recipient.
     * Recipient
     * @return Returns the GetRecipientResponse
     */
    public GetRecipientResponse getRecipient() {
        return OptionalNullable.getFrom(recipient);
    }

    /**
     * Setter for Recipient.
     * Recipient
     * @param recipient Value for GetRecipientResponse
     */
    @JsonSetter("recipient")
    public void setRecipient(GetRecipientResponse recipient) {
        this.recipient = OptionalNullable.of(recipient);
    }

    /**
     * UnSetter for Recipient.
     * Recipient
     */
    public void unsetRecipient() {
        recipient = null;
    }

    /**
     * Internal Getter for TransferredAmount.
     * @return Returns the Internal Long
     */
    @JsonGetter("transferred_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Long> internalGetTransferredAmount() {
        return this.transferredAmount;
    }

    /**
     * Getter for TransferredAmount.
     * @return Returns the Long
     */
    public Long getTransferredAmount() {
        return OptionalNullable.getFrom(transferredAmount);
    }

    /**
     * Setter for TransferredAmount.
     * @param transferredAmount Value for Long
     */
    @JsonSetter("transferred_amount")
    public void setTransferredAmount(Long transferredAmount) {
        this.transferredAmount = OptionalNullable.of(transferredAmount);
    }

    /**
     * UnSetter for TransferredAmount.
     */
    public void unsetTransferredAmount() {
        transferredAmount = null;
    }

    /**
     * Internal Getter for WaitingFundsAmount.
     * @return Returns the Internal Long
     */
    @JsonGetter("waiting_funds_amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Long> internalGetWaitingFundsAmount() {
        return this.waitingFundsAmount;
    }

    /**
     * Getter for WaitingFundsAmount.
     * @return Returns the Long
     */
    public Long getWaitingFundsAmount() {
        return OptionalNullable.getFrom(waitingFundsAmount);
    }

    /**
     * Setter for WaitingFundsAmount.
     * @param waitingFundsAmount Value for Long
     */
    @JsonSetter("waiting_funds_amount")
    public void setWaitingFundsAmount(Long waitingFundsAmount) {
        this.waitingFundsAmount = OptionalNullable.of(waitingFundsAmount);
    }

    /**
     * UnSetter for WaitingFundsAmount.
     */
    public void unsetWaitingFundsAmount() {
        waitingFundsAmount = null;
    }

    /**
     * Converts this GetBalanceResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetBalanceResponse [" + "currency=" + currency + ", availableAmount="
                + availableAmount + ", recipient=" + recipient + ", transferredAmount="
                + transferredAmount + ", waitingFundsAmount=" + waitingFundsAmount + "]";
    }

    /**
     * Builds a new {@link GetBalanceResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetBalanceResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.currency = internalGetCurrency();
        builder.availableAmount = internalGetAvailableAmount();
        builder.recipient = internalGetRecipient();
        builder.transferredAmount = internalGetTransferredAmount();
        builder.waitingFundsAmount = internalGetWaitingFundsAmount();
        return builder;
    }

    /**
     * Class to build instances of {@link GetBalanceResponse}.
     */
    public static class Builder {
        private OptionalNullable<String> currency;
        private OptionalNullable<Long> availableAmount;
        private OptionalNullable<GetRecipientResponse> recipient;
        private OptionalNullable<Long> transferredAmount;
        private OptionalNullable<Long> waitingFundsAmount;



        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = OptionalNullable.of(currency);
            return this;
        }

        /**
         * UnSetter for currency.
         * @return Builder
         */
        public Builder unsetCurrency() {
            currency = null;
            return this;
        }

        /**
         * Setter for availableAmount.
         * @param  availableAmount  Long value for availableAmount.
         * @return Builder
         */
        public Builder availableAmount(Long availableAmount) {
            this.availableAmount = OptionalNullable.of(availableAmount);
            return this;
        }

        /**
         * UnSetter for availableAmount.
         * @return Builder
         */
        public Builder unsetAvailableAmount() {
            availableAmount = null;
            return this;
        }

        /**
         * Setter for recipient.
         * @param  recipient  GetRecipientResponse value for recipient.
         * @return Builder
         */
        public Builder recipient(GetRecipientResponse recipient) {
            this.recipient = OptionalNullable.of(recipient);
            return this;
        }

        /**
         * UnSetter for recipient.
         * @return Builder
         */
        public Builder unsetRecipient() {
            recipient = null;
            return this;
        }

        /**
         * Setter for transferredAmount.
         * @param  transferredAmount  Long value for transferredAmount.
         * @return Builder
         */
        public Builder transferredAmount(Long transferredAmount) {
            this.transferredAmount = OptionalNullable.of(transferredAmount);
            return this;
        }

        /**
         * UnSetter for transferredAmount.
         * @return Builder
         */
        public Builder unsetTransferredAmount() {
            transferredAmount = null;
            return this;
        }

        /**
         * Setter for waitingFundsAmount.
         * @param  waitingFundsAmount  Long value for waitingFundsAmount.
         * @return Builder
         */
        public Builder waitingFundsAmount(Long waitingFundsAmount) {
            this.waitingFundsAmount = OptionalNullable.of(waitingFundsAmount);
            return this;
        }

        /**
         * UnSetter for waitingFundsAmount.
         * @return Builder
         */
        public Builder unsetWaitingFundsAmount() {
            waitingFundsAmount = null;
            return this;
        }

        /**
         * Builds a new {@link GetBalanceResponse} object using the set fields.
         * @return {@link GetBalanceResponse}
         */
        public GetBalanceResponse build() {
            return new GetBalanceResponse(currency, availableAmount, recipient, transferredAmount,
                    waitingFundsAmount);
        }
    }
}
