/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.BaseModel;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for GetGatewayErrorResponse type.
 */
public class GetGatewayErrorResponse {
    private OptionalNullable<String> message;

    /**
     * Default constructor.
     */
    public GetGatewayErrorResponse() {
    }

    /**
     * Initialization constructor.
     * @param  message  String value for message.
     */
    public GetGatewayErrorResponse(
            String message) {
        this.message = OptionalNullable.of(message);
    }

    /**
     * Internal initialization constructor.
     */
    protected GetGatewayErrorResponse(OptionalNullable<String> message) {
        this.message = message;
    }

    /**
     * Internal Getter for Message.
     * The message error
     * @return Returns the Internal String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetMessage() {
        return this.message;
    }

    /**
     * Getter for Message.
     * The message error
     * @return Returns the String
     */
    public String getMessage() {
        return OptionalNullable.getFrom(message);
    }

    /**
     * Setter for Message.
     * The message error
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = OptionalNullable.of(message);
    }

    /**
     * UnSetter for Message.
     * The message error
     */
    public void unsetMessage() {
        message = null;
    }

    /**
     * Converts this GetGatewayErrorResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetGatewayErrorResponse [" + "message=" + message + "]";
    }

    /**
     * Builds a new {@link GetGatewayErrorResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetGatewayErrorResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.message = internalGetMessage();
        return builder;
    }

    /**
     * Class to build instances of {@link GetGatewayErrorResponse}.
     */
    public static class Builder {
        private OptionalNullable<String> message;



        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = OptionalNullable.of(message);
            return this;
        }

        /**
         * UnSetter for message.
         * @return Builder
         */
        public Builder unsetMessage() {
            message = null;
            return this;
        }

        /**
         * Builds a new {@link GetGatewayErrorResponse} object using the set fields.
         * @return {@link GetGatewayErrorResponse}
         */
        public GetGatewayErrorResponse build() {
            return new GetGatewayErrorResponse(message);
        }
    }
}
