/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import me.pagar.api.DateTimeHelper;

/**
 * This is a model class for GetIncrementResponse type.
 */
public class GetIncrementResponse {
    private String id;
    private double value;
    private String incrementType;
    private String status;
    private LocalDateTime createdAt;
    private Integer cycles;
    private LocalDateTime deletedAt;
    private String description;
    private GetSubscriptionResponse subscription;
    private GetSubscriptionItemResponse subscriptionItem;

    /**
     * Default constructor.
     */
    public GetIncrementResponse() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  value  double value for value.
     * @param  incrementType  String value for incrementType.
     * @param  status  String value for status.
     * @param  createdAt  LocalDateTime value for createdAt.
     * @param  cycles  Integer value for cycles.
     * @param  deletedAt  LocalDateTime value for deletedAt.
     * @param  description  String value for description.
     * @param  subscription  GetSubscriptionResponse value for subscription.
     * @param  subscriptionItem  GetSubscriptionItemResponse value for subscriptionItem.
     */
    public GetIncrementResponse(
            String id,
            double value,
            String incrementType,
            String status,
            LocalDateTime createdAt,
            Integer cycles,
            LocalDateTime deletedAt,
            String description,
            GetSubscriptionResponse subscription,
            GetSubscriptionItemResponse subscriptionItem) {
        this.id = id;
        this.value = value;
        this.incrementType = incrementType;
        this.status = status;
        this.createdAt = createdAt;
        this.cycles = cycles;
        this.deletedAt = deletedAt;
        this.description = description;
        this.subscription = subscription;
        this.subscriptionItem = subscriptionItem;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Value.
     * @return Returns the double
     */
    @JsonGetter("value")
    public double getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for double
     */
    @JsonSetter("value")
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Getter for IncrementType.
     * @return Returns the String
     */
    @JsonGetter("increment_type")
    public String getIncrementType() {
        return incrementType;
    }

    /**
     * Setter for IncrementType.
     * @param incrementType Value for String
     */
    @JsonSetter("increment_type")
    public void setIncrementType(String incrementType) {
        this.incrementType = incrementType;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for CreatedAt.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("created_at")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * @param createdAt Value for LocalDateTime
     */
    @JsonSetter("created_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for Cycles.
     * @return Returns the Integer
     */
    @JsonGetter("cycles")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCycles() {
        return cycles;
    }

    /**
     * Setter for Cycles.
     * @param cycles Value for Integer
     */
    @JsonSetter("cycles")
    public void setCycles(Integer cycles) {
        this.cycles = cycles;
    }

    /**
     * Getter for DeletedAt.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("deleted_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    /**
     * Setter for DeletedAt.
     * @param deletedAt Value for LocalDateTime
     */
    @JsonSetter("deleted_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Subscription.
     * @return Returns the GetSubscriptionResponse
     */
    @JsonGetter("subscription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public GetSubscriptionResponse getSubscription() {
        return subscription;
    }

    /**
     * Setter for Subscription.
     * @param subscription Value for GetSubscriptionResponse
     */
    @JsonSetter("subscription")
    public void setSubscription(GetSubscriptionResponse subscription) {
        this.subscription = subscription;
    }

    /**
     * Getter for SubscriptionItem.
     * The Subscription Item
     * @return Returns the GetSubscriptionItemResponse
     */
    @JsonGetter("subscription_item")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public GetSubscriptionItemResponse getSubscriptionItem() {
        return subscriptionItem;
    }

    /**
     * Setter for SubscriptionItem.
     * The Subscription Item
     * @param subscriptionItem Value for GetSubscriptionItemResponse
     */
    @JsonSetter("subscription_item")
    public void setSubscriptionItem(GetSubscriptionItemResponse subscriptionItem) {
        this.subscriptionItem = subscriptionItem;
    }

    /**
     * Converts this GetIncrementResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetIncrementResponse [" + "id=" + id + ", value=" + value + ", incrementType="
                + incrementType + ", status=" + status + ", createdAt=" + createdAt + ", cycles="
                + cycles + ", deletedAt=" + deletedAt + ", description=" + description
                + ", subscription=" + subscription + ", subscriptionItem=" + subscriptionItem + "]";
    }

    /**
     * Builds a new {@link GetIncrementResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetIncrementResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, value, incrementType, status, createdAt)
                .cycles(getCycles())
                .deletedAt(getDeletedAt())
                .description(getDescription())
                .subscription(getSubscription())
                .subscriptionItem(getSubscriptionItem());
        return builder;
    }

    /**
     * Class to build instances of {@link GetIncrementResponse}.
     */
    public static class Builder {
        private String id;
        private double value;
        private String incrementType;
        private String status;
        private LocalDateTime createdAt;
        private Integer cycles;
        private LocalDateTime deletedAt;
        private String description;
        private GetSubscriptionResponse subscription;
        private GetSubscriptionItemResponse subscriptionItem;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  value  double value for value.
         * @param  incrementType  String value for incrementType.
         * @param  status  String value for status.
         * @param  createdAt  LocalDateTime value for createdAt.
         */
        public Builder(String id, double value, String incrementType, String status,
                LocalDateTime createdAt) {
            this.id = id;
            this.value = value;
            this.incrementType = incrementType;
            this.status = status;
            this.createdAt = createdAt;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for value.
         * @param  value  double value for value.
         * @return Builder
         */
        public Builder value(double value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for incrementType.
         * @param  incrementType  String value for incrementType.
         * @return Builder
         */
        public Builder incrementType(String incrementType) {
            this.incrementType = incrementType;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @return Builder
         */
        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for cycles.
         * @param  cycles  Integer value for cycles.
         * @return Builder
         */
        public Builder cycles(Integer cycles) {
            this.cycles = cycles;
            return this;
        }

        /**
         * Setter for deletedAt.
         * @param  deletedAt  LocalDateTime value for deletedAt.
         * @return Builder
         */
        public Builder deletedAt(LocalDateTime deletedAt) {
            this.deletedAt = deletedAt;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for subscription.
         * @param  subscription  GetSubscriptionResponse value for subscription.
         * @return Builder
         */
        public Builder subscription(GetSubscriptionResponse subscription) {
            this.subscription = subscription;
            return this;
        }

        /**
         * Setter for subscriptionItem.
         * @param  subscriptionItem  GetSubscriptionItemResponse value for subscriptionItem.
         * @return Builder
         */
        public Builder subscriptionItem(GetSubscriptionItemResponse subscriptionItem) {
            this.subscriptionItem = subscriptionItem;
            return this;
        }

        /**
         * Builds a new {@link GetIncrementResponse} object using the set fields.
         * @return {@link GetIncrementResponse}
         */
        public GetIncrementResponse build() {
            return new GetIncrementResponse(id, value, incrementType, status, createdAt, cycles,
                    deletedAt, description, subscription, subscriptionItem);
        }
    }
}
