/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for GetSplitOptionsResponse type.
 */
public class GetSplitOptionsResponse {
    private Boolean liable;
    private Boolean chargeProcessingFee;
    private String chargeRemainderFee;

    /**
     * Default constructor.
     */
    public GetSplitOptionsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  liable  Boolean value for liable.
     * @param  chargeProcessingFee  Boolean value for chargeProcessingFee.
     * @param  chargeRemainderFee  String value for chargeRemainderFee.
     */
    public GetSplitOptionsResponse(
            Boolean liable,
            Boolean chargeProcessingFee,
            String chargeRemainderFee) {
        this.liable = liable;
        this.chargeProcessingFee = chargeProcessingFee;
        this.chargeRemainderFee = chargeRemainderFee;
    }

    /**
     * Getter for Liable.
     * @return Returns the Boolean
     */
    @JsonGetter("liable")
    public Boolean getLiable() {
        return liable;
    }

    /**
     * Setter for Liable.
     * @param liable Value for Boolean
     */
    @JsonSetter("liable")
    public void setLiable(Boolean liable) {
        this.liable = liable;
    }

    /**
     * Getter for ChargeProcessingFee.
     * @return Returns the Boolean
     */
    @JsonGetter("charge_processing_fee")
    public Boolean getChargeProcessingFee() {
        return chargeProcessingFee;
    }

    /**
     * Setter for ChargeProcessingFee.
     * @param chargeProcessingFee Value for Boolean
     */
    @JsonSetter("charge_processing_fee")
    public void setChargeProcessingFee(Boolean chargeProcessingFee) {
        this.chargeProcessingFee = chargeProcessingFee;
    }

    /**
     * Getter for ChargeRemainderFee.
     * @return Returns the String
     */
    @JsonGetter("charge_remainder_fee")
    public String getChargeRemainderFee() {
        return chargeRemainderFee;
    }

    /**
     * Setter for ChargeRemainderFee.
     * @param chargeRemainderFee Value for String
     */
    @JsonSetter("charge_remainder_fee")
    public void setChargeRemainderFee(String chargeRemainderFee) {
        this.chargeRemainderFee = chargeRemainderFee;
    }

    /**
     * Converts this GetSplitOptionsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetSplitOptionsResponse [" + "liable=" + liable + ", chargeProcessingFee="
                + chargeProcessingFee + ", chargeRemainderFee=" + chargeRemainderFee + "]";
    }

    /**
     * Builds a new {@link GetSplitOptionsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetSplitOptionsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(liable, chargeProcessingFee, chargeRemainderFee);
        return builder;
    }

    /**
     * Class to build instances of {@link GetSplitOptionsResponse}.
     */
    public static class Builder {
        private Boolean liable;
        private Boolean chargeProcessingFee;
        private String chargeRemainderFee;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  liable  Boolean value for liable.
         * @param  chargeProcessingFee  Boolean value for chargeProcessingFee.
         * @param  chargeRemainderFee  String value for chargeRemainderFee.
         */
        public Builder(Boolean liable, Boolean chargeProcessingFee, String chargeRemainderFee) {
            this.liable = liable;
            this.chargeProcessingFee = chargeProcessingFee;
            this.chargeRemainderFee = chargeRemainderFee;
        }

        /**
         * Setter for liable.
         * @param  liable  Boolean value for liable.
         * @return Builder
         */
        public Builder liable(Boolean liable) {
            this.liable = liable;
            return this;
        }

        /**
         * Setter for chargeProcessingFee.
         * @param  chargeProcessingFee  Boolean value for chargeProcessingFee.
         * @return Builder
         */
        public Builder chargeProcessingFee(Boolean chargeProcessingFee) {
            this.chargeProcessingFee = chargeProcessingFee;
            return this;
        }

        /**
         * Setter for chargeRemainderFee.
         * @param  chargeRemainderFee  String value for chargeRemainderFee.
         * @return Builder
         */
        public Builder chargeRemainderFee(String chargeRemainderFee) {
            this.chargeRemainderFee = chargeRemainderFee;
            return this;
        }

        /**
         * Builds a new {@link GetSplitOptionsResponse} object using the set fields.
         * @return {@link GetSplitOptionsResponse}
         */
        public GetSplitOptionsResponse build() {
            return new GetSplitOptionsResponse(liable, chargeProcessingFee, chargeRemainderFee);
        }
    }
}
